get http://localhost:3003/api/blogs

###
get http://localhost:3003/api/users

###
// This request needs the token that's returned from
// from the POST /api/login for a user.
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbW1pdGFoIiwiaWQiOiI2MzMzNTQ2NTE2YzVlZDRkZWIyMDI3MmUiLCJpYXQiOjE2NjQzNjYyNTh9.lkCcLAMUamwKH9-DaoKSFzrtLrGGxjGNOk7LeI47dJw 

{
    "title": "Words of Radiance",
    "author": "Brandon Sanderson",
    "url": "https://coppermind.net/wiki/Words_of_Radiance",
    "likes": 5000000,
    "user": "6333546516c5ed4deb20272e"
}

###
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbW1pdGFoIiwiaWQiOiI2MzMzNTQ2NTE2YzVlZDRkZWIyMDI3MmUiLCJpYXQiOjE2NjQzNjYyNTh9.lkCcLAMUamwKH9-DaoKSFzrtLrGGxjGNOk7LeI47dJw 

{
    "title": "Oathbringer",
    "author": "Brandon Sanderson",
    "url": "https://coppermind.net/wiki/Oathbringer",
    "likes": 6000000,
    "user": "6333546516c5ed4deb20272e"
}

###
post http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "tommitah",
    "password": "smeghoidbond"
}

###
// id 633440c59775c667f62b35a6
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "djommidah",
    "password": "mongoose"
}

###
// token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRqb21taWRhaCIsImlkIjoiNjMzNDQwYzU5Nzc1YzY2N2Y2MmIzNWE2IiwiaWF0IjoxNjY0MzY4OTIzLCJleHAiOjE2NjQzNzI1MjN9.fVsI1PjnJp0lCLnTnqnSYYnnyV7LGI9OGN2E1HSWEW0
post http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "djommidah",
    "password": "mongoose"
}

###
delete http://localhost:3003/api/blogs/633436d13c8b4e85dd2c91e2
Content-Type: application/json
// djommidah:
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRqb21taWRhaCIsImlkIjoiNjMzNDQwYzU5Nzc1YzY2N2Y2MmIzNWE2IiwiaWF0IjoxNjY0MzY4OTIzLCJleHAiOjE2NjQzNzI1MjN9.fVsI1PjnJp0lCLnTnqnSYYnnyV7LGI9OGN2E1HSWEW0
// tommitah:
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbW1pdGFoIiwiaWQiOiI2MzMzNTQ2NTE2YzVlZDRkZWIyMDI3MmUiLCJpYXQiOjE2NjQzNjYyNTh9.lkCcLAMUamwKH9-DaoKSFzrtLrGGxjGNOk7LeI47dJw 
